# Generated by Django 2.0.2 on 2018-05-06 13:42

import UI.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facedatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('image1', models.ImageField(upload_to=UI.models.content_file_name1)),
                ('image2', models.ImageField(upload_to=UI.models.content_file_name2)),
                ('image3', models.ImageField(upload_to=UI.models.content_file_name3)),
                ('image4', models.ImageField(upload_to=UI.models.content_file_name3)),
                ('image5', models.ImageField(upload_to=UI.models.content_file_name3)),
                ('dob', models.DateField()),
                ('crime', models.DateField()),
                ('Injail', models.CharField(max_length=264)),
                ('gang', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=264)),
            ],
        ),
    ]
