# Generated by Django 2.0.2 on 2018-05-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facedatabase',
            old_name='crime',
            new_name='dod',
        ),
    ]
