# Generated by Django 2.0.2 on 2018-05-06 13:49

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_auto_20180506_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedatabase',
            name='image4',
            field=models.ImageField(upload_to=UI.models.content_file_name4),
        ),
        migrations.AlterField(
            model_name='facedatabase',
            name='image5',
            field=models.ImageField(upload_to=UI.models.content_file_name5),
        ),
    ]
